### ISSUE TITLE
Group tabs by open windows

### ISSUE THREAD

**Issue by AlexWayfer** [kallepersson/tabswitcher#2]
Hello!

I open Tab Switcher in one of open windows and see tabs in this window.

But it will be cool if I can see tabs from other windows below some… spoiler / header? And by click focus on this window and tab.

Thanks.

**Comment by kallepersson** [comment]
Patches welcome :)

On Thu, 15 Dec 2016 at 22:20, Alexander Popov <notifications@github.com>
wrote:

Hello!

I open Tab Switcher in one of open windows and see tabs in this window.

But it will be cool if I can see tabs from other windows below some…
spoiler / header? And by click focus on this window and tab.

Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kallepersson/tabswitcher/issues/2>, or mute the thread
